---

- hosts: i2pd
  remote_user: root
  tasks:
  - name: Upgrading apt
    apt:
      update_cache: true
      allow_unauthenticated: true
      upgrade: true

  - name: Adding APT key
    apt_key:
      keyserver: keys.gnupg.net
      id: 66F6C87B98EBCFE2
  
  - name: Installing HTTPS transport for APT
    apt:
      name: apt-transport-https
      state: present
      
  - name: Setup ntp package
    apt: 
      name: ntp 
      state: present

  - name: Enable ntpd service 
    service: 
      name: ntp 
      state: started
      enabled: yes

  - name: Install CA certificates
    apt:
      name: ca-certificates
      state: present

  - name: Setup missing package(s) for Debian
    apt: 
      name: dirmngr
      state: present

  - name: Enable Debian repository
    apt_repository:
      repo: "deb http://repo.lngserv.ru/debian {{ ansible_distribution_release }} main"
      state: present
      filename: 'i2pd'

  - name: Setup i2pd package
    apt: 
      name: i2pd
      state: present

  - name: Enable i2pd service
    service: 
      name: i2pd 
      state: started 
      enabled: yes